### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by renanortiz** [twilio/twilio-cli#350]
### Issue Summary
After installing twilio-cli globally, running any twilio command in terminal I receive "command not found"
(worked normally few days ago)

### Steps to Reproduce
1. npm install -g twilio-cli
2. twilio

### Code Snippet
+ twilio
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (twilio:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

+ Get-Command twilio
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (twilio:String) [Get-Command], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Microsoft.PowerShell.Commands.GetCommandCommand

### Technical details:
* twilio-cli version: 
* node version: v16.13.1

Already tried Uninstalling and Installing again

**Comment by onuzbee** [comment]
Hey @renanortiz Could you help us with the `twilio-cli` version you're on? 
Meanwhile- Can see you're on Windows powershell, would suggest doing the following and checking if the issue is mitigated:

- Clean current global `twilio-cli` installation currently on system
- Try out recently added Scoop installation method: Install [scoop](https://scoop.sh/)
- Install Twilio-cli using scoop from here: https://github.com/twilio/scoop-twilio-cli

**Comment by renanortiz** [comment]
Anyway to check the version without using the twilio command?

Steps taken:
npm uninstall twilio-cli -g
installed scoop
installed twilio-cli using scoop

It worked, twilio-cli/2.35.0 win32-x64 node-v16.13.0
Thankss
